export { Cryptocurrencies } from './Cryptocurrencies'
export { Homepage } from './Homepage'
export { Exchanges } from './Exchanges'
export { default as News } from './News'
export { CryptoDetails } from './CryptoDetails'